name: health
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - jupyterlab
  - ipywidgets
  - notebook
  - tqdm
  - plotly
  - faker
  - pip